### PR TITLE
first commit wrote Hello There in c

### LINKED ISSUE #7: Add Hello There with C
Add the C code that would display Hello There! on screen.

Following instructions in #6

### PR DESCRIPTION
**Pull request by ridonky**
## Linked Issue

Closes #7

## Description

I have written "Hello There!" in C

## Code of Conduct

 By submitting this pull request, you agree to follow our [Code of Conduct](https://github.com/ClJarvis/Hello_There/blob/main/Code_of_Conduct)

### CODE REVIEW

**Comment by Dnyanesh-Bachhav** [comment]
Hey, do I need to do anything else??
and 
my pull request had merged or not??

**Comment by ClJarvis** [comment]
@ridonky Please a a link to some C documentation on how to  print 'Hello World'.  Put the link in a comment.

Thank you.

**Comment by ridonky** [comment]
Sure, here is a link to documentation that shows how to compile and run the program that prints 'hello there': https://vitux.com/how-to-write-and-run-a-c-program-in-linux/

**Comment by ClJarvis** [comment]
Obi wan Hello There

**Pull request merged**
